### ISSUE TITLE
Dokumentide salvestamine PostgreSQL-is

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/RIHA-Storage#1]
Praegu salvestatakse tabelis `document` ainult dokumendi metaandmed. Dokument ise salvestatakse failisüsteemis. Vaja on dokumendid ise ka salvestada andmebaasis. Lisada vastav blob-väli ja teha muudatused Java-loogikas.

**Comment by KertuHiire** [comment]
Dokumentide salvestamine realiseeritud postgreSQLi large_object funktsionaalsust kasutades 
versioonis 0.7.0 (https://github.com/e-gov/RIHA-Storage/releases/tag/v0.7.0)
